### PR TITLE
Fix modulo operations

### LINKED ISSUE #261: Check that all modulo operations are being done correctly

### PR DESCRIPTION
**Pull request by entropidelic**
Resolves #261

Replace all modulo operations in the code where the `%` was being used to a `mod_floor()` method call.

### CODE REVIEW

**Review by fmoletta — APPROVED** [review]
Nice Work!

File: src/utils.rs [hunk 1]
```diff
@@ -54,7 +55,7 @@ pub fn from_relocatable_to_indexes(relocatable: Relocatable) -> (usize, usize) {
 ///equivalent to val modulo prime.
 pub fn to_field_element(num: BigInt, prime: BigInt) -> BigInt {
     let half_prime = prime.clone() / bigint!(2);
```
Comment (Juan-M-V) [inline src/utils.rs:57]: Idk if this is out of scope for the PR, but the half prime could be calculated with a shift right and the addition could be calculated with a ref instead of cloning

Comment (entropidelic) [reply src/utils.rs]: I think it was a bit out of scope but since it is very little change I made it

Comment (Juan-M-V) [reply src/utils.rs]: Nice! Thanks!

**Review by Juan-M-V — APPROVED** [review]
